export default {
    "Control": {
        "Status": 1,
        "Message": "Success"
    },
    "Data": {
        "Products": [{
                "MRP": 166,
                "SP": 137,
                "storeLandLineNumber": "2210645425",
                "storePAN": "COUJB5689O",
                "CategoryName": "Namkeen",
                "ProductName": "Haldiram Boondi",
                "StoreProductId": "100052078",
                "ProductImage": "https://jiomerchantsit.akamaized.net/static/product/17-47-301568578526.jpg",
                "StorePincode": "411001",
                "StoreLocation": "19.12648,73.011009",
                "StoreName": "Global Downtown Store",
                "ProductSkuId": 10021332,
                "ProductSkuName": "370",
                "UpdatedSP": 127,
                "BrandName": "Haldiram Mixtures",
                "ProductId": 100018321,
                "ProductLastUpdatedDate": "2018-07-12 15:19:56",
                "StoreId": "1175669",
                "IsFc": 0,
                "BrandId": 206,
                "CategoryId": 275,
                "Barcode": "8904063200464",
                "Coupons": {
                    "Description": "Haldiram Boondi Haldiram Boondi",
                    "Source": "discover",
                    "Status": 0,
                    "Code": "$GENERATE_PER_CUSTOMER",
                    "LikeCount": 0,
                    "UserGroup": 42,
                    "Id": 3678,
                    "LikedDate": 0,
                    "EndDate": 1573151340000,
                    "CouponBuckets": null,
                    "Locations": null,
                    "Categories": [
                        205,
                        20205,
                        30205
                    ],
                    "Title": "10 off on Haldiram Boondi",
                    "CouponType": 2,
                    "MerchantGroup": 581,
                    "Merchant": 0,
                    "MerchantName": "Kissan",
                    "Terms": "Haldiram Boondi Haldiram Boondi",
                    "MerchantRedeemCap": 100,
                    "MaxRedeem": 10000,
                    "DiscountPercentageValue": 0,
                    "DiscountMax": null,
                    "DiscountAbsValue": 10,
                    "DiscountMinBill": 0,
                    "DiscountType": "FLAT_DISCOUNT_WITH_SKU",
                    "SkuOffer": [],
                    "CdnMerchantImageURL": "https://jiocoupons-st.akamaized.net/images/l,00000001.jpeg",
                    "CdnBrandImageId": "https://jiocoupons-st.akamaized.net/images/l,00000001.jpeg",
                    "CdnImageURL": "https://jiocoupons-st.akamaized.net/images/igVC3ugoLy3gU29tkAp73A",
                    "Brand": 98679,
                    "StartDate": 1559068200000,
                    "ReductionType": "0",
                    "ImageURL": "/cr/v2/coupons/images/igVC3ugoLy3gU29tkAp73A",
                    "MerchantPhone": null,
                    "MerchantUrl": null,
                    "CouponUrl": "https://google.com",
                    "AffiliateUrl": null,
                    "DiscountExtraRules": "Discount Discount Discount Discount",
                    "CouponTag": "Exclusive",
                    "BannerName": null,
                    "BannerImageId": null,
                    "MerchantImageId": "/cr/v2/coupons/images/l,00000001.jpeg",
                    "Details": null,
                    "CreateTs": 1559125789000,
                    "Note": null,
                    "Sticker": null,
                    "RedeemDayhour": 2147483647,
                    "RedeemGender": 0,
                    "RedeemMinAge": 0,
                    "RedeemMaxAge": 150,
                    "RedeemLocation": 0,
                    "RedeemExempDates": null,
                    "DownloadCap": 0,
                    "RedeemCap": 1001,
                    "PushType": 0,
                    "VendorCId": null,
                    "SkuConditions": [{
                        "Sku": 10021332,
                        "Quantity": 1,
                        "Name": "Haldiram Boondi",
                        "SellingPrice": null,
                        "ActualPrice": null
                    }],
                    "MerchantGroupName": "581",
                    "Tags": [],
                    "ExemptDates": null,
                    "CouponLabel": "Haldiram Boondi Haldiram Boondi",
                    "BrandImageId": "/cr/v2/coupons/images/l,00000001.jpeg",
                    "BrandName": "Kissan",
                    "CdnSponsorImageURL": "https://jiocoupons-st.akamaized.net/images/l,00000001.jpeg",
                    "SkuId": null,
                    "Quantity": null,
                    "Price": null,
                    "Coupons": null
                },
                "CategoryIds": [
                    1,
                    62,
                    275
                ],
                "CategoryNames": [
                    "Kirana / Provision store / Supermarket",
                    "Snacks",
                    "Namkeen"
                ],
                "EntityBarcodeId": "102871260",
                "EntityBarcodeStatus": "1",
                "CGST": "0",
                "IGST": "0",
                "SGST": "0",
                "CESS": "0",
                "ADC": "0",
                "IndustryId": "1",
                "CompanyName": "Haldiram Snacks Pvt Ltd",
                "ProductAlias": "Haldiram Boondi 370 gms",
                "StoreOwnProductId": 0,
                "StoreProductBatchId": "100052078",
                "StoreEmail": "primemerchant@ril.com",
                "StoreMobileNumber": "9821565543"
            },
            {
                "MRP": 175,
                "SP": 127,
                "storeLandLineNumber": "2210645425",
                "storePAN": "COUJB5689O",
                "CategoryName": "Namkeen",
                "ProductName": "Haldiram Boondi Plain",
                "StoreProductId": "100052077",
                "ProductImage": "https://jiomerchantsit.akamaized.net/static/product/17-47-301568578526.jpg",
                "StorePincode": "411001",
                "StoreLocation": "19.12648,73.011009",
                "StoreName": "Global Downtown Store",
                "ProductSkuId": 10021331,
                "ProductSkuName": "200",
                "BrandName": "Haldiram Mixtures",
                "ProductId": 100018320,
                "ProductLastUpdatedDate": "2018-07-12 15:19:56",
                "StoreId": "1175669",
                "IsFc": 0,
                "BrandId": 206,
                "CategoryId": 275,
                "Barcode": "871265502086",
                "CategoryIds": [
                    1,
                    62,
                    275
                ],
                "CategoryNames": [
                    "Kirana / Provision store / Supermarket",
                    "Snacks",
                    "Namkeen"
                ],
                "EntityBarcodeId": "102871259",
                "EntityBarcodeStatus": "1",
                "CGST": "0",
                "IGST": "0",
                "SGST": "0",
                "CESS": "0",
                "ADC": "0",
                "IndustryId": "1",
                "CompanyName": "Haldiram Snacks Pvt Ltd",
                "ProductAlias": "Haldiram Boondi Plain 200 gms",
                "StoreOwnProductId": 0,
                "StoreProductBatchId": "100052077",
                "StoreEmail": "primemerchant@ril.com",
                "StoreMobileNumber": "9821565543"
            },
            {
                "MRP": 65,
                "SP": 45,
                "storeLandLineNumber": "2210645425",
                "storePAN": "COUJB5689O",
                "CategoryName": "Bhujia",
                "ProductName": "Haldiram Bhujia",
                "StoreProductId": "100052369",
                "ProductImage": "https://jiomerchantsit.akamaized.net/static/product/bhujia-hal-AaramShop-10.jpg",
                "StorePincode": "400701",
                "StoreLocation": "19.12648,73.011009",
                "StoreName": "Global Downtown Store",
                "ProductSkuId": 10002712,
                "ProductSkuName": "200",
                "BrandName": "Haldiram Mixtures",
                "ProductId": 100002227,
                "ProductLastUpdatedDate": "2018-07-12 15:19:56",
                "StoreId": "1175669",
                "IsFc": 0,
                "BrandId": 206,
                "CategoryId": 273,
                "Barcode": "8904063200051",
                "CategoryIds": [
                    1,
                    290,
                    273
                ],
                "CategoryNames": [
                    "Kirana / Provision store / Supermarket",
                    "Salt & Sugar",
                    "Bhujia"
                ],
                "EntityBarcodeId": "102871551",
                "EntityBarcodeStatus": "1",
                "CGST": "0",
                "IGST": "0",
                "SGST": "0",
                "CESS": "0",
                "ADC": "0",
                "IndustryId": "1",
                "CompanyName": "Haldiram Snacks Pvt Ltd",
                "ProductAlias": "Haldiram Bhujia 200 gms",
                "StoreOwnProductId": 0,
                "StoreProductBatchId": "100052369",
                "StoreEmail": "primemerchant@ril.com",
                "StoreMobileNumber": "9821565543"
            },
            {
                "MRP": 188,
                "SP": 137,
                "storeLandLineNumber": "2210645425",
                "storePAN": "COUJB5689O",
                "CategoryName": "Bhujia",
                "ProductName": "Haldiram Bhujia",
                "StoreProductId": "100051755",
                "ProductImage": "https://jiomerchantsit.akamaized.net/static/product/bhujia-hal-AaramShop-83.jpg",
                "StorePincode": "400701",
                "StoreLocation": "19.12648,73.011009",
                "StoreName": "Global Downtown Store",
                "ProductSkuId": 10002711,
                "ProductSkuName": "1",
                "BrandName": "Haldiram Mixtures",
                "ProductId": 100002227,
                "ProductLastUpdatedDate": "2018-07-12 15:19:56",
                "StoreId": "1175669",
                "IsFc": 0,
                "BrandId": 206,
                "CategoryId": 273,
                "Barcode": "8904063200945",
                "CategoryIds": [
                    1,
                    290,
                    273
                ],
                "CategoryNames": [
                    "Kirana / Provision store / Supermarket",
                    "Salt & Sugar",
                    "Bhujia"
                ],
                "EntityBarcodeId": "102870937",
                "EntityBarcodeStatus": "1",
                "CGST": "0",
                "IGST": "0",
                "SGST": "0",
                "CESS": "0",
                "ADC": "0",
                "IndustryId": "1",
                "CompanyName": "Haldiram Snacks Pvt Ltd",
                "ProductAlias": "Haldiram Bhujia 1 kg",
                "StoreOwnProductId": 0,
                "StoreProductBatchId": "100051755",
                "StoreEmail": "primemerchant@ril.com",
                "StoreMobileNumber": "9821565543"
            },
            {
                "MRP": 165,
                "SP": 115,
                "storeLandLineNumber": "2210645425",
                "storePAN": "COUJB5689O",
                "CategoryName": "Mixture",
                "ProductName": "Haldiram Allin One Mixture",
                "StoreProductId": "100052027",
                "ProductImage": "https://jiomerchantsit.akamaized.net/static/product/14553621761.jpg",
                "StorePincode": "411001",
                "StoreLocation": "19.12648,73.011009",
                "StoreName": "Global Downtown Store",
                "ProductSkuId": 10020440,
                "ProductSkuName": "200",
                "BrandName": "Haldiram Mixtures",
                "ProductId": 100017544,
                "ProductLastUpdatedDate": "2018-07-12 15:19:56",
                "StoreId": "1175669",
                "IsFc": 0,
                "BrandId": 206,
                "CategoryId": 63,
                "Barcode": "871265502024",
                "CategoryIds": [
                    1,
                    62,
                    63
                ],
                "CategoryNames": [
                    "Kirana / Provision store / Supermarket",
                    "Snacks",
                    "Mixture"
                ],
                "EntityBarcodeId": "102871209",
                "EntityBarcodeStatus": "1",
                "CGST": "0",
                "IGST": "0",
                "SGST": "0",
                "CESS": "0",
                "ADC": "0",
                "IndustryId": "1",
                "CompanyName": "Haldiram Snacks Pvt Ltd",
                "ProductAlias": "Haldiram Allin One Mixture 200 gms",
                "StoreOwnProductId": 0,
                "StoreProductBatchId": "100052027",
                "StoreEmail": "primemerchant@ril.com",
                "StoreMobileNumber": "9821565543"
            },
            {
                "MRP": 166,
                "SP": 137,
                "storeLandLineNumber": "2210645425",
                "storePAN": "COUJB5689O",
                "CategoryName": "Bhujia",
                "ProductName": "Haldirams Aloo Bhujia",
                "StoreProductId": "100051722",
                "ProductImage": "https://jiomerchantsit.akamaized.net/static/product/Aloo_Bhujia-AaramShop-95.jpg",
                "StorePincode": "411001",
                "StoreLocation": "19.12648,73.011009",
                "StoreName": "Global Downtown Store",
                "ProductSkuId": 10001013,
                "ProductSkuName": "1",
                "BrandName": "Haldiram Mixtures",
                "ProductId": 100000898,
                "ProductLastUpdatedDate": "2018-07-12 15:19:56",
                "StoreId": "1175669",
                "IsFc": 0,
                "BrandId": 206,
                "CategoryId": 273,
                "Barcode": "8904063200938",
                "CategoryIds": [
                    1,
                    290,
                    273
                ],
                "CategoryNames": [
                    "Kirana / Provision store / Supermarket",
                    "Salt & Sugar",
                    "Bhujia"
                ],
                "EntityBarcodeId": "102870904",
                "EntityBarcodeStatus": "1",
                "CGST": "0",
                "IGST": "0",
                "SGST": "0",
                "CESS": "0",
                "ADC": "0",
                "IndustryId": "1",
                "CompanyName": "Haldiram Snacks Pvt Ltd",
                "ProductAlias": "Haldirams Aloo Bhujia 1 kg",
                "StoreOwnProductId": 0,
                "StoreProductBatchId": "100051722",
                "StoreEmail": "primemerchant@ril.com",
                "StoreMobileNumber": "9821565543"
            },
            {
                "MRP": 175,
                "SP": 127,
                "storeLandLineNumber": "2210645425",
                "storePAN": "COUJB5689O",
                "CategoryName": "Bhujia",
                "ProductName": "Haldirams Aloo Bhujia",
                "StoreProductId": "100052368",
                "ProductImage": "https://jiomerchantsit.akamaized.net/static/product/Aloo_Bhujia-AaramShop-93.jpg",
                "StorePincode": "400701",
                "StoreLocation": "19.12648,73.011009",
                "StoreName": "Global Downtown Store",
                "ProductSkuId": 10001014,
                "ProductSkuName": "200",
                "BrandName": "Haldiram Mixtures",
                "ProductId": 100000898,
                "ProductLastUpdatedDate": "2018-07-12 15:19:56",
                "StoreId": "1175669",
                "IsFc": 0,
                "BrandId": 206,
                "CategoryId": 273,
                "Barcode": "8904063200013",
                "CategoryIds": [
                    1,
                    290,
                    273
                ],
                "CategoryNames": [
                    "Kirana / Provision store / Supermarket",
                    "Salt & Sugar",
                    "Bhujia"
                ],
                "EntityBarcodeId": "102871550",
                "EntityBarcodeStatus": "1",
                "CGST": "0",
                "IGST": "0",
                "SGST": "0",
                "CESS": "0",
                "ADC": "0",
                "IndustryId": "1",
                "CompanyName": "Haldiram Snacks Pvt Ltd",
                "ProductAlias": "Haldirams Aloo Bhujia 200 gms",
                "StoreOwnProductId": 0,
                "StoreProductBatchId": "100052368",
                "StoreEmail": "primemerchant@ril.com",
                "StoreMobileNumber": "9821565543"
            },
            {
                "MRP": 188,
                "SP": 137,
                "storeLandLineNumber": "2210645425",
                "storePAN": "COUJB5689O",
                "CategoryName": "Mixture",
                "ProductName": "Haldirams Cornflakes Mixture",
                "StoreProductId": "100052029",
                "ProductImage": "https://jiomerchantsit.akamaized.net/static/product/cornflakes-mixture-200gms-AaramShop-85.jpg",
                "StorePincode": "400701",
                "StoreLocation": "19.12648,73.011009",
                "StoreName": "Global Downtown Store",
                "ProductSkuId": 10020446,
                "ProductSkuName": "200",
                "BrandName": "Haldiram Mixtures",
                "ProductId": 100017549,
                "ProductLastUpdatedDate": "2018-07-12 15:19:56",
                "StoreId": "1175669",
                "IsFc": 0,
                "BrandId": 206,
                "CategoryId": 63,
                "Barcode": "8904063200105",
                "CategoryIds": [
                    1,
                    62,
                    63
                ],
                "CategoryNames": [
                    "Kirana / Provision store / Supermarket",
                    "Snacks",
                    "Mixture"
                ],
                "EntityBarcodeId": "102871211",
                "EntityBarcodeStatus": "1",
                "CGST": "0",
                "IGST": "0",
                "SGST": "0",
                "CESS": "0",
                "ADC": "0",
                "IndustryId": "1",
                "CompanyName": "Haldiram Snacks Pvt Ltd",
                "ProductAlias": "Haldirams Cornflakes Mixture 200 gms",
                "StoreOwnProductId": 0,
                "StoreProductBatchId": "100052029",
                "StoreEmail": "primemerchant@ril.com",
                "StoreMobileNumber": "9821565543"
            },
            {
                "MRP": 165,
                "SP": 115,
                "storeLandLineNumber": "2210645425",
                "storePAN": "COUJB5689O",
                "CategoryName": "Bhujia",
                "ProductName": "Haldirams Plain Bhujia",
                "StoreProductId": "100051756",
                "ProductImage": "https://jiomerchantsit.akamaized.net/static/product/07-49-461660976827.jpg",
                "StorePincode": "411001",
                "StoreLocation": "19.12648,73.011009",
                "StoreName": "Global Downtown Store",
                "ProductSkuId": 10002713,
                "ProductSkuName": "200",
                "UpdatedSP": 100,
                "BrandName": "Haldiram Mixtures",
                "ProductId": 100002228,
                "ProductLastUpdatedDate": "2018-07-12 15:19:56",
                "StoreId": "1175669",
                "IsFc": 0,
                "BrandId": 206,
                "CategoryId": 273,
                "Barcode": "8904063200068",
                "Coupons": {
                    "Description": "Haldirams Plain Bhujia Haldirams Plain Bhujia",
                    "Source": "discover",
                    "Status": 0,
                    "Code": "$GENERATE_PER_CUSTOMER",
                    "LikeCount": 0,
                    "UserGroup": 42,
                    "Id": 3680,
                    "LikedDate": 0,
                    "EndDate": 1573842540000,
                    "CouponBuckets": null,
                    "Locations": null,
                    "Categories": [
                        207,
                        30207,
                        20207
                    ],
                    "Title": "15 off on Haldirams Plain Bhujia",
                    "CouponType": 2,
                    "MerchantGroup": 581,
                    "Merchant": 0,
                    "MerchantName": "Lifebuoy",
                    "Terms": "Haldirams Plain Bhujia Haldirams Plain Bhujia",
                    "MerchantRedeemCap": 100,
                    "MaxRedeem": 1000,
                    "DiscountPercentageValue": 0,
                    "DiscountMax": null,
                    "DiscountAbsValue": 15,
                    "DiscountMinBill": 0,
                    "DiscountType": "FLAT_DISCOUNT_WITH_SKU",
                    "SkuOffer": [],
                    "CdnMerchantImageURL": "https://jiocoupons-st.akamaized.net/images/l,00000001.jpeg",
                    "CdnBrandImageId": "https://jiocoupons-st.akamaized.net/images/l,00000001.jpeg",
                    "CdnImageURL": "https://jiocoupons-st.akamaized.net/images/igVC3ugqLy3gU29tkAp73A",
                    "Brand": 98704,
                    "StartDate": 1559068200000,
                    "ReductionType": "0",
                    "ImageURL": "/cr/v2/coupons/images/igVC3ugqLy3gU29tkAp73A",
                    "MerchantPhone": null,
                    "MerchantUrl": null,
                    "CouponUrl": "https://google.com",
                    "AffiliateUrl": null,
                    "DiscountExtraRules": "Discount Discount Discount Discount",
                    "CouponTag": "Exclusive",
                    "BannerName": null,
                    "BannerImageId": null,
                    "MerchantImageId": "/cr/v2/coupons/images/l,00000001.jpeg",
                    "Details": null,
                    "CreateTs": 1559126064000,
                    "Note": null,
                    "Sticker": null,
                    "RedeemDayhour": 2147483647,
                    "RedeemGender": 0,
                    "RedeemMinAge": 0,
                    "RedeemMaxAge": 150,
                    "RedeemLocation": 0,
                    "RedeemExempDates": null,
                    "DownloadCap": 0,
                    "RedeemCap": 100,
                    "PushType": 0,
                    "VendorCId": null,
                    "SkuConditions": [{
                        "Sku": 10002713,
                        "Quantity": 1,
                        "Name": "Haldirams Plain Bhujia",
                        "SellingPrice": null,
                        "ActualPrice": null
                    }],
                    "MerchantGroupName": "581",
                    "Tags": [],
                    "ExemptDates": null,
                    "CouponLabel": "Haldirams Plain Bhujia Haldirams Plain Bhujia",
                    "BrandImageId": "/cr/v2/coupons/images/l,00000001.jpeg",
                    "BrandName": "Lifebuoy",
                    "CdnSponsorImageURL": "https://jiocoupons-st.akamaized.net/images/l,00000001.jpeg",
                    "SkuId": null,
                    "Quantity": null,
                    "Price": null,
                    "Coupons": null
                },
                "CategoryIds": [
                    1,
                    290,
                    273
                ],
                "CategoryNames": [
                    "Kirana / Provision store / Supermarket",
                    "Salt & Sugar",
                    "Bhujia"
                ],
                "EntityBarcodeId": "102870938",
                "EntityBarcodeStatus": "1",
                "CGST": "0",
                "IGST": "0",
                "SGST": "0",
                "CESS": "0",
                "ADC": "0",
                "IndustryId": "1",
                "CompanyName": "Haldiram Snacks Pvt Ltd",
                "ProductAlias": "Haldirams Plain Bhujia 200 gms",
                "StoreOwnProductId": 0,
                "StoreProductBatchId": "100051756",
                "StoreEmail": "primemerchant@ril.com",
                "StoreMobileNumber": "9821565543"
            },
            {
                "MRP": 165,
                "SP": 115,
                "storeLandLineNumber": "2210645425",
                "storePAN": "COUJB5689O",
                "CategoryName": "Namkeen",
                "ProductName": "Haldirams Dal Biji",
                "StoreProductId": "100052071",
                "ProductImage": "https://jiomerchantsit.akamaized.net/static/product/dal-bhaji-AaramShop-25.jpg",
                "StorePincode": "411001",
                "StoreLocation": "19.12648,73.011009",
                "StoreName": "Global Downtown Store",
                "ProductSkuId": 10021311,
                "ProductSkuName": "200",
                "BrandName": "Haldiram Mixtures",
                "ProductId": 100018304,
                "ProductLastUpdatedDate": "2018-07-12 15:19:56",
                "StoreId": "1175669",
                "IsFc": 0,
                "BrandId": 206,
                "CategoryId": 275,
                "Barcode": "8904063253606",
                "CategoryIds": [
                    1,
                    62,
                    275
                ],
                "CategoryNames": [
                    "Kirana / Provision store / Supermarket",
                    "Snacks",
                    "Namkeen"
                ],
                "EntityBarcodeId": "102871253",
                "EntityBarcodeStatus": "1",
                "CGST": "0",
                "IGST": "0",
                "SGST": "0",
                "CESS": "0",
                "ADC": "0",
                "IndustryId": "1",
                "CompanyName": "Haldiram Snacks Pvt Ltd",
                "ProductAlias": "Haldirams Dal Biji 200 gms",
                "StoreOwnProductId": 0,
                "StoreProductBatchId": "100052071",
                "StoreEmail": "primemerchant@ril.com",
                "StoreMobileNumber": "9821565543"
            },
            {
                "MRP": 166,
                "SP": 123.3,
                "storeLandLineNumber": "2210645425",
                "storePAN": "COUJB5689O",
                "CategoryName": "Mixture",
                "ProductName": "Haldirams Khatta Meetha",
                "StoreProductId": "100052268",
                "ProductImage": "https://jiomerchantsit.akamaized.net/static/product/Haldirams-Khatta-Meetha-AaramShop-36.jpg",
                "StorePincode": "400701",
                "StoreLocation": "19.12648,73.011009",
                "StoreName": "Global Downtown Store",
                "ProductSkuId": 10020444,
                "ProductSkuName": "400",
                "BrandName": "Haldiram Mixtures",
                "ProductId": 100017547,
                "ProductLastUpdatedDate": "2018-07-12 15:19:56",
                "StoreId": "1175669",
                "IsFc": 0,
                "BrandId": 206,
                "CategoryId": 63,
                "Barcode": "8904063230140",
                "Coupons": {
                    "Description": "Haldirams Khatta Meetha -Haldirams Khatta Meetha -",
                    "Source": "discover",
                    "Status": 0,
                    "Code": "$GENERATE_PER_CUSTOMER",
                    "LikeCount": 0,
                    "UserGroup": 42,
                    "Id": 3679,
                    "LikedDate": 0,
                    "EndDate": 1571423340000,
                    "CouponBuckets": null,
                    "Locations": null,
                    "Categories": [
                        20206,
                        206,
                        30206
                    ],
                    "Title": "10% off on Haldirams Khatta Meetha -",
                    "CouponType": 2,
                    "MerchantGroup": 581,
                    "Merchant": 0,
                    "MerchantName": "MTR",
                    "Terms": "Haldirams Khatta Meetha -Haldirams Khatta Meetha -",
                    "MerchantRedeemCap": 100,
                    "MaxRedeem": 1000,
                    "DiscountPercentageValue": 100,
                    "DiscountMax": 20,
                    "DiscountAbsValue": 100,
                    "DiscountMinBill": 0,
                    "DiscountType": "PERCENTAGE_DISCOUNT_WITH_SKU",
                    "SkuOffer": [],
                    "CdnMerchantImageURL": "https://jiocoupons-st.akamaized.net/images/l,00000001.jpeg",
                    "CdnBrandImageId": "https://jiocoupons-st.akamaized.net/images/l,00000001.jpeg",
                    "CdnImageURL": "https://jiocoupons-st.akamaized.net/images/igVC3ugpLy3gU29tkAp73A",
                    "Brand": 100922,
                    "StartDate": 1559068200000,
                    "ReductionType": "0",
                    "ImageURL": "/cr/v2/coupons/images/igVC3ugpLy3gU29tkAp73A",
                    "MerchantPhone": null,
                    "MerchantUrl": null,
                    "CouponUrl": "https://google.com",
                    "AffiliateUrl": null,
                    "DiscountExtraRules": "Discount Discount Discount Discount",
                    "CouponTag": "Exclusive",
                    "BannerName": null,
                    "BannerImageId": null,
                    "MerchantImageId": "/cr/v2/coupons/images/l,00000001.jpeg",
                    "Details": null,
                    "CreateTs": 1559125929000,
                    "Note": null,
                    "Sticker": null,
                    "RedeemDayhour": 2147483647,
                    "RedeemGender": 0,
                    "RedeemMinAge": 0,
                    "RedeemMaxAge": 150,
                    "RedeemLocation": 0,
                    "RedeemExempDates": null,
                    "DownloadCap": 0,
                    "RedeemCap": 100,
                    "PushType": 0,
                    "VendorCId": null,
                    "SkuConditions": [{
                        "Sku": 10020444,
                        "Quantity": 1,
                        "Name": "Haldirams Khatta Meetha -",
                        "SellingPrice": null,
                        "ActualPrice": null
                    }],
                    "MerchantGroupName": "581",
                    "Tags": [],
                    "ExemptDates": null,
                    "CouponLabel": "Haldirams Khatta Meetha -Haldirams Khatta Meetha -",
                    "BrandImageId": "/cr/v2/coupons/images/l,00000001.jpeg",
                    "BrandName": "MTR",
                    "CdnSponsorImageURL": "https://jiocoupons-st.akamaized.net/images/l,00000001.jpeg",
                    "SkuId": null,
                    "Quantity": null,
                    "Price": null,
                    "Coupons": null
                },
                "CategoryIds": [
                    1,
                    62,
                    63
                ],
                "CategoryNames": [
                    "Kirana / Provision store / Supermarket",
                    "Snacks",
                    "Mixture"
                ],
                "EntityBarcodeId": "102871450",
                "EntityBarcodeStatus": "1",
                "CGST": "0",
                "IGST": "0",
                "SGST": "0",
                "CESS": "0",
                "ADC": "0",
                "IndustryId": "1",
                "CompanyName": "Haldiram Snacks Pvt Ltd",
                "ProductAlias": "Haldirams Khatta Meetha 400 gms",
                "StoreOwnProductId": 0,
                "StoreProductBatchId": "100052268",
                "StoreEmail": "primemerchant@ril.com",
                "StoreMobileNumber": "9821565543"
            },
            {
                "MRP": 166,
                "SP": 137,
                "storeLandLineNumber": "2210645425",
                "storePAN": "COUJB5689O",
                "CategoryName": "Mixture",
                "ProductName": "Haldirams Khatta Meetha",
                "StoreProductId": "100052028",
                "ProductImage": "https://jiomerchantsit.akamaized.net/static/product/haldi-ram-khatta-meeth-200gms-AaramShop-65.jpg",
                "StorePincode": "400701",
                "StoreLocation": "19.12648,73.011009",
                "StoreName": "Global Downtown Store",
                "ProductSkuId": 10020443,
                "ProductSkuName": "200",
                "BrandName": "Haldiram Mixtures",
                "ProductId": 100017547,
                "ProductLastUpdatedDate": "2018-07-12 15:19:56",
                "StoreId": "1175669",
                "IsFc": 0,
                "BrandId": 206,
                "CategoryId": 63,
                "Barcode": "8904063240224",
                "CategoryIds": [
                    1,
                    62,
                    63
                ],
                "CategoryNames": [
                    "Kirana / Provision store / Supermarket",
                    "Snacks",
                    "Mixture"
                ],
                "EntityBarcodeId": "102871210",
                "EntityBarcodeStatus": "1",
                "CGST": "0",
                "IGST": "0",
                "SGST": "0",
                "CESS": "0",
                "ADC": "0",
                "IndustryId": "1",
                "CompanyName": "Haldiram Snacks Pvt Ltd",
                "ProductAlias": "Haldirams Khatta Meetha 200 gms",
                "StoreOwnProductId": 0,
                "StoreProductBatchId": "100052028",
                "StoreEmail": "primemerchant@ril.com",
                "StoreMobileNumber": "9821565543"
            }
        ],
        "Count": 0,
        "Filters": [{
                "text": "Categories",
                "id": "categoryName",
                "selection": "Multiple",
                "types": [{
                        "id": null,
                        "value": null,
                        "text": "bhujia"
                    },
                    {
                        "id": null,
                        "value": null,
                        "text": "mixture"
                    },
                    {
                        "id": null,
                        "value": null,
                        "text": "namkeen"
                    }
                ]
            },
            {
                "text": "Brands",
                "id": "brandName",
                "selection": "Multiple",
                "types": [{
                    "id": null,
                    "value": null,
                    "text": "haldiram mixtures"
                }]
            },
            {
                "text": "Stores",
                "id": "storeName",
                "selection": "Multiple",
                "types": [{
                    "id": null,
                    "value": null,
                    "text": "global downtown store"
                }]
            },
            {
                "text": "Ratings",
                "id": "ratings",
                "selection": "Single",
                "types": [{
                        "id": null,
                        "value": null,
                        "text": "0.0-1.0"
                    },
                    {
                        "id": null,
                        "value": null,
                        "text": "1.0-2.0"
                    },
                    {
                        "id": null,
                        "value": null,
                        "text": "2.0-3.0"
                    },
                    {
                        "id": null,
                        "value": null,
                        "text": "3.0-4.0"
                    },
                    {
                        "id": null,
                        "value": null,
                        "text": "4.0-5.0"
                    }
                ]
            },
            {
                "text": "Sort By",
                "id": "sort",
                "selection": "Single",
                "types": [{
                        "id": "SP",
                        "value": "desc",
                        "text": "Price High to Low"
                    },
                    {
                        "id": "SP",
                        "value": "asc",
                        "text": "Price Low to High"
                    },
                    {
                        "id": "expressDelivery",
                        "value": "desc",
                        "text": "Express Delivery"
                    },
                    {
                        "id": "productName",
                        "value": "asc",
                        "text": "Alphabetical"
                    }
                ]
            }
        ]
    }
}