// app
export const START_FETCH = 'START_FETCH';
export const SUCCESS_FETCH = 'SUCCESS_FETCH';
export const FAIL_FETCH = 'FAIL_FETCH';
export const COMPLETE_AUTH = 'COMPLETE_AUTH';
export const TOGGLE_SPINNER = 'TOGGLE_SPINNER';
export const TOGGLE_SNACKBAR = 'TOGGLE_SNACKBAR';
export const ALERT_BOX = 'ALERT_BOX';
export const REMOVE_AUTH = 'REMOVE_AUTH';
export const READY_APP = 'READY_APP';
export const TOGGLE_HAMBURGER = 'TOGGLE_HAMBURGER';
export const TOGGLE_LOCATION = 'TOGGLE_LOCATION';

// user
export const SET_USER = 'SET_USER';
export const NEW_USER = 'NEW_USER';
export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN';
export const SET_NEW_AUTH_TOKEN = 'SET_NEW_AUTH_TOKEN';
export const ORDER_RATED = 'ORDER_RATED';

// address
export const SELECT_ADDRESS = 'SELECT_ADDRESS';
export const UNSELECT_ADDRESS = 'UNSELECT_ADDRESS';
export const ADD_ADDRESS = 'ADD_ADDRESS';
export const ADDRESS_LIST_SET_DEFAULT = 'ADDRESS_LIST_SET_DEFAULT';
export const UPDATE_ADDRESS_LIST = 'UPDATE_ADDRESS_LIST';
export const REMOVE_ADDRESS_LIST = 'REMOVE_ADDRESS_LIST';
export const SET_LAT_LNG = 'SET_LAT_LNG';
export const CHANGE_KIRANA = 'CHANGE_KIRANA';
export const SET_LAT_LNG_ADDRESSES = 'SET_LAT_LNG_ADDRESSES';

// header
export const CHANGE_ROUTE = 'CHANGE_ROUTE';

// Filters
export const SET_SORT_FILTERS = 'SET_SORT_FILTERS';
export const SET_FILTER_OPTIONS = 'SET_FILTER_OPTIONS';
export const SET_ORDER_FILTERS = 'SET_ORDER_FILTERS';
