export default {
    "Control": {
        "Message": "success",
        "MessageCode": 200,
        "TimeTaken": 26000000,
        "Status": 1
    },
    "Data": {
        "widgets": [
            {
                "type": 1,
                "subType": 1,
                "title": "",
                "deepLink": "",
                "deepLinkText": "",
                "bgColor": "",
                "data": {
                    "products": null,
                    "miscellaneous": [
                        {
                            "imageUrl": "https://pp-static.jiomoney.com/static/capp/android/drawable-xhdpi/category_atta.png",
                            "deepLink": "",
                            "name": "Atta, Dals & Rice",
                            "mscId": 1,
                            "imageResolutionSupport": 1
                        },
                        {
                            "imageUrl": "https://pp-static.jiomoney.com/static/capp/android/drawable-xhdpi/category_oil.png",
                            "deepLink": "",
                            "name": "Oils & Ghee",
                            "mscId": 2,
                            "imageResolutionSupport": 1
                        },
                        {
                            "imageUrl": "https://pp-static.jiomoney.com/static/capp/android/drawable-xhdpi/category_breakfast.png",
                            "deepLink": "",
                            "name": "Breakfast & Dairy",
                            "mscId": 3,
                            "imageResolutionSupport": 1
                        },
                        {
                            "imageUrl": "https://pp-static.jiomoney.com/static/capp/android/drawable-xhdpi/category_sugar.png",
                            "deepLink": "",
                            "name": "Sugar & Salt",
                            "mscId": 4,
                            "imageResolutionSupport": 1
                        },
                        {
                            "imageUrl": "https://pp-static.jiomoney.com/static/capp/android/drawable-xhdpi/category_atta.png",
                            "deepLink": "",
                            "name": "Atta, Dals & Rice",
                            "mscId": 5,
                            "imageResolutionSupport": 1
                        },
                        {
                            "imageUrl": "https://pp-static.jiomoney.com/static/capp/android/drawable-xhdpi/category_oil.png",
                            "deepLink": "",
                            "name": "Oils & Ghee",
                            "mscId": 6,
                            "imageResolutionSupport": 1
                        },
                        {
                            "imageUrl": "https://pp-static.jiomoney.com/static/capp/android/drawable-xhdpi/category_breakfast.png",
                            "deepLink": "",
                            "name": "Breakfast & Dairy",
                            "mscId": 7,
                            "imageResolutionSupport": 1
                        }
                    ],
                    "stores": null,
                    "banners": null
                }
            },
            {
                "type": 2,
                "subType": 1,
                "title": "",
                "deepLink": "",
                "deepLinkText": "",
                "bgColor": "",
                "data": {
                    "products": null,
                    "miscellaneous": null,
                    "stores": null,
                    "banners": [
                        {
                            "imageUrl": "https://jiomerchantsit.akamaized.net/static/capp/ios/3x/DettolBanner.png",
                            "deepLink": "",
                            "bannerId": 1,
                            "imageResolutionSupport": 1
                        },
                        {
                            "imageUrl": "https://jiomerchantsit.akamaized.net/static/capp/ios/3x/Ice-cream-Banner.png",
                            "deepLink": "",
                            "bannerId": 2,
                            "imageResolutionSupport": 1
                        },
                        {
                            "imageUrl": "https://jiomerchantsit.akamaized.net/static/capp/ios/3x/MANGO-BANNER.png",
                            "deepLink": "",
                            "bannerId": 3,
                            "imageResolutionSupport": 1
                        }, {
                            "imageUrl": "https://jiomerchantsit.akamaized.net/static/capp/ios/3x/DettolBanner.png",
                            "deepLink": "",
                            "bannerId": 1,
                            "imageResolutionSupport": 1
                        },
                        {
                            "imageUrl": "https://jiomerchantsit.akamaized.net/static/capp/ios/3x/Ice-cream-Banner.png",
                            "deepLink": "",
                            "bannerId": 2,
                            "imageResolutionSupport": 1
                        },
                        {
                            "imageUrl": "https://jiomerchantsit.akamaized.net/static/capp/ios/3x/MANGO-BANNER.png",
                            "deepLink": "",
                            "bannerId": 3,
                            "imageResolutionSupport": 1
                        }
                    ]
                }
            },
            {
                "type": 3,
                "subType": 1,
                "title": "TODAY'S DEALS",
                "deepLink": "",
                "deepLinkText": "See more",
                "bgColor": "",
                "data": {
                    "products": [
                        {
                            "ProductId": 100015385,
                            "ProductName": "Nestea Iced Tea Lemon Flavour",
                            "CategoryId": 177,
                            "ProductSKU": null,
                            "ProductSkuId": 10017970,
                            "ProductImage": "https://jiomerchantsit.akamaized.net/static/product/nesteaicedtealemonflavour500-aaramshop.jpg",
                            "MRP": 65,
                            "BrandId": 108,
                            "ProductSKUUQCFullName": null,
                            "BrandName": "Nestea",
                            "OfferText": null,
                            "CompanyName": "Nestle India Limited",
                            "IsPrime": true,
                            "ProductSKUUQCId": null,
                            "ProductSKUUQC": null,
                            "IsCoupon": true,
                            "ProductOtherImage": null,
                            "ProductSKUUQCShortName": null,
                            "SP": 45,
                            "IsOffer": null,
                            "Express": null,
                            "IsFavoriate": null,
                            "CompanyId": null,
                            "ProductBarcodeId": null,
                            "Barcode": "8901058816563",
                            "CategoryName": "Ice Tea",
                            "CouponResult": null,
                            "isFc": 0
                        },
                        {
                            "ProductId": 100009282,
                            "ProductName": "Nivea Whitening Fruity Deodorant For Women",
                            "CategoryId": 10000697,
                            "ProductSKU": null,
                            "ProductSkuId": 10010675,
                            "ProductImage": "https://jiomerchantsit.akamaized.net/static/product/1460613833.jpg",
                            "MRP": 65,
                            "BrandId": 89,
                            "ProductSKUUQCFullName": null,
                            "BrandName": "Nivea Deodarants",
                            "OfferText": null,
                            "CompanyName": "Nivea India Pvt. Ltd. (Beiersdorf AG)",
                            "IsPrime": null,
                            "ProductSKUUQCId": null,
                            "ProductSKUUQC": null,
                            "IsCoupon": null,
                            "ProductOtherImage": null,
                            "ProductSKUUQCShortName": null,
                            "SP": 45,
                            "IsOffer": null,
                            "Express": null,
                            "IsFavoriate": null,
                            "CompanyId": null,
                            "ProductBarcodeId": null,
                            "Barcode": "4005808667758",
                            "CategoryName": "Deodorants",
                            "CouponResult": null,
                            "isFc": 0
                        },
                        {
                            "ProductId": 100041181,
                            "ProductName": "Sunsilk Soya Vitamin Complex Shampoo",
                            "CategoryId": 10000987,
                            "ProductSKU": null,
                            "ProductSkuId": 10046844,
                            "ProductImage": "https://jiomerchantsit.akamaized.net/static/product/1460011488.jpg",
                            "MRP": 165,
                            "BrandId": 21,
                            "ProductSKUUQCFullName": null,
                            "BrandName": "Sunsilk",
                            "OfferText": null,
                            "CompanyName": "Hindustan Unilever",
                            "IsPrime": true,
                            "ProductSKUUQCId": null,
                            "ProductSKUUQC": null,
                            "IsCoupon": true,
                            "ProductOtherImage": null,
                            "ProductSKUUQCShortName": null,
                            "SP": 115,
                            "IsOffer": null,
                            "Express": null,
                            "IsFavoriate": null,
                            "CompanyId": null,
                            "ProductBarcodeId": null,
                            "Barcode": "8901030445767",
                            "CategoryName": "Hair Shampoo",
                            "CouponResult": null,
                            "isFc": 0
                        },
                        {
                            "ProductId": 100005099,
                            "ProductName": "Lays Classic Salted",
                            "CategoryId": 75,
                            "ProductSKU": null,
                            "ProductSkuId": 10047934,
                            "ProductImage": "https://jiomerchantsit.akamaized.net/static/product/no_image_found.png",
                            "MRP": 65,
                            "BrandId": 1869,
                            "ProductSKUUQCFullName": null,
                            "BrandName": "Lays",
                            "OfferText": null,
                            "CompanyName": "PepsiCo India",
                            "IsPrime": null,
                            "ProductSKUUQCId": null,
                            "ProductSKUUQC": null,
                            "IsCoupon": null,
                            "ProductOtherImage": null,
                            "ProductSKUUQCShortName": null,
                            "SP": 45,
                            "IsOffer": null,
                            "Express": null,
                            "IsFavoriate": null,
                            "CompanyId": null,
                            "ProductBarcodeId": null,
                            "Barcode": "8901491101837",
                            "CategoryName": "Chips",
                            "CouponResult": null,
                            "isFc": 0
                        },
                        {
                            "ProductId": 100015385,
                            "ProductName": "Nestea Iced Tea Lemon Flavour",
                            "CategoryId": 177,
                            "ProductSKU": null,
                            "ProductSkuId": 10017970,
                            "ProductImage": "https://jiomerchantsit.akamaized.net/static/product/nesteaicedtealemonflavour500-aaramshop.jpg",
                            "MRP": 65,
                            "BrandId": 108,
                            "ProductSKUUQCFullName": null,
                            "BrandName": "Nestea",
                            "OfferText": null,
                            "CompanyName": "Nestle India Limited",
                            "IsPrime": null,
                            "ProductSKUUQCId": null,
                            "ProductSKUUQC": null,
                            "IsCoupon": null,
                            "ProductOtherImage": null,
                            "ProductSKUUQCShortName": null,
                            "SP": 45,
                            "IsOffer": null,
                            "Express": null,
                            "IsFavoriate": null,
                            "CompanyId": null,
                            "ProductBarcodeId": null,
                            "Barcode": "8901058816563",
                            "CategoryName": "Ice Tea",
                            "CouponResult": null,
                            "isFc": 0
                        },
                        {
                            "ProductId": 100009282,
                            "ProductName": "Nivea Whitening Fruity Deodorant For Women",
                            "CategoryId": 10000697,
                            "ProductSKU": null,
                            "ProductSkuId": 10010675,
                            "ProductImage": "https://jiomerchantsit.akamaized.net/static/product/1460613833.jpg",
                            "MRP": 65,
                            "BrandId": 89,
                            "ProductSKUUQCFullName": null,
                            "BrandName": "Nivea Deodarants",
                            "OfferText": null,
                            "CompanyName": "Nivea India Pvt. Ltd. (Beiersdorf AG)",
                            "IsPrime": null,
                            "ProductSKUUQCId": null,
                            "ProductSKUUQC": null,
                            "IsCoupon": null,
                            "ProductOtherImage": null,
                            "ProductSKUUQCShortName": null,
                            "SP": 45,
                            "IsOffer": null,
                            "Express": null,
                            "IsFavoriate": null,
                            "CompanyId": null,
                            "ProductBarcodeId": null,
                            "Barcode": "4005808667758",
                            "CategoryName": "Deodorants",
                            "CouponResult": null,
                            "isFc": 0
                        },
                        {
                            "ProductId": 100018859,
                            "ProductName": "Bagrrys Porridge White Oats Jar",
                            "CategoryId": 78,
                            "ProductSKU": null,
                            "ProductSkuId": 10022013,
                            "ProductImage": "https://jiomerchantsit.akamaized.net/static/product/14547424781.jpg",
                            "MRP": 65,
                            "BrandId": 672,
                            "ProductSKUUQCFullName": null,
                            "BrandName": "Bagrrys",
                            "OfferText": null,
                            "CompanyName": "Bagrrys India Limited",
                            "IsPrime": null,
                            "ProductSKUUQCId": null,
                            "ProductSKUUQC": null,
                            "IsCoupon": null,
                            "ProductOtherImage": null,
                            "ProductSKUUQCShortName": null,
                            "SP": 45,
                            "IsOffer": null,
                            "Express": null,
                            "IsFavoriate": null,
                            "CompanyId": null,
                            "ProductBarcodeId": null,
                            "Barcode": "8902710100112",
                            "CategoryName": "Oats",
                            "CouponResult": null,
                            "isFc": 0
                        },
                        {
                            "ProductId": 100010947,
                            "ProductName": "Clearasil Daily Use Facewash",
                            "CategoryId": 10001132,
                            "ProductSKU": null,
                            "ProductSkuId": 10012682,
                            "ProductImage": "https://jiomerchantsit.akamaized.net/static/product/12-25-421976706774.jpg",
                            "MRP": 65,
                            "BrandId": 290,
                            "ProductSKUUQCFullName": null,
                            "BrandName": "Clearasil",
                            "OfferText": null,
                            "CompanyName": "Reckitt Benckiser",
                            "IsPrime": null,
                            "ProductSKUUQCId": null,
                            "ProductSKUUQC": null,
                            "IsCoupon": null,
                            "ProductOtherImage": null,
                            "ProductSKUUQCShortName": null,
                            "SP": 45,
                            "IsOffer": null,
                            "Express": null,
                            "IsFavoriate": null,
                            "CompanyId": null,
                            "ProductBarcodeId": null,
                            "Barcode": "8901396608004",
                            "CategoryName": "Face Wash",
                            "CouponResult": null,
                            "isFc": 0
                        },
                        {
                            "ProductId": 100001160,
                            "ProductName": "Aashirvaad Atta With Multigrains",
                            "CategoryId": 120,
                            "ProductSKU": null,
                            "ProductSkuId": 10001303,
                            "ProductImage": "https://jiomerchantsit.akamaized.net/static/product/04-17-28848812574.jpg",
                            "MRP": 65,
                            "BrandId": 370,
                            "ProductSKUUQCFullName": null,
                            "BrandName": "Aashirvaad",
                            "OfferText": null,
                            "CompanyName": "ITC Limited",
                            "IsPrime": null,
                            "ProductSKUUQCId": null,
                            "ProductSKUUQC": null,
                            "IsCoupon": null,
                            "ProductOtherImage": null,
                            "ProductSKUUQCShortName": null,
                            "SP": 45,
                            "IsOffer": null,
                            "Express": null,
                            "IsFavoriate": null,
                            "CompanyId": null,
                            "ProductBarcodeId": null,
                            "Barcode": "8901725121624",
                            "CategoryName": "Atta",
                            "CouponResult": null,
                            "isFc": 0
                        },
                        {
                            "ProductId": 1000003914,
                            "ProductName": "Gillette Mach3 Manual Shaving Razor Blades Cartridges",
                            "CategoryId": 156,
                            "ProductSKU": null,
                            "ProductSkuId": 10004556,
                            "ProductImage": "https://jiomerchantsit.akamaized.net/static/product/Gillette-Mach3-Manual-12-AaramShop-95.jpg",
                            "MRP": 65,
                            "BrandId": 67,
                            "ProductSKUUQCFullName": null,
                            "BrandName": "Gillette",
                            "OfferText": null,
                            "CompanyName": "Procter & Gamble India Ltd",
                            "IsPrime": null,
                            "ProductSKUUQCId": null,
                            "ProductSKUUQC": null,
                            "IsCoupon": null,
                            "ProductOtherImage": null,
                            "ProductSKUUQCShortName": null,
                            "SP": 45,
                            "IsOffer": null,
                            "Express": null,
                            "IsFavoriate": null,
                            "CompanyId": null,
                            "ProductBarcodeId": null,
                            "Barcode": "4902430658270",
                            "CategoryName": "Cartridges",
                            "CouponResult": null,
                            "isFc": 0
                        },
                        {
                            "ProductId": 100014452,
                            "ProductName": "Complan For Growth Natural",
                            "CategoryId": 10002160,
                            "ProductSKU": null,
                            "ProductSkuId": 10016816,
                            "ProductImage": "https://jiomerchantsit.akamaized.net/static/product/1457936081.jpg",
                            "MRP": 65,
                            "BrandId": 2094,
                            "ProductSKUUQCFullName": null,
                            "BrandName": "Complan",
                            "OfferText": null,
                            "CompanyName": "The Kraft Heinz Company",
                            "IsPrime": null,
                            "ProductSKUUQCId": null,
                            "ProductSKUUQC": null,
                            "IsCoupon": null,
                            "ProductOtherImage": null,
                            "ProductSKUUQCShortName": null,
                            "SP": 45,
                            "IsOffer": null,
                            "Express": null,
                            "IsFavoriate": null,
                            "CompanyId": null,
                            "ProductBarcodeId": null,
                            "Barcode": "8901542013607",
                            "CategoryName": "Health Drinks",
                            "CouponResult": null,
                            "isFc": 0
                        },
                        {
                            "ProductId": 100005203,
                            "ProductName": "Cadbury Gems",
                            "CategoryId": 90,
                            "ProductSKU": null,
                            "ProductSkuId": 10006009,
                            "ProductImage": "https://jiomerchantsit.akamaized.net/static/product/gems_AaramShop1.jpg",
                            "MRP": 65,
                            "BrandId": 1257,
                            "ProductSKUUQCFullName": null,
                            "BrandName": "Cadbury Gems",
                            "OfferText": null,
                            "CompanyName": "Mondelez India Foods Pvt Ltd (Formerly Cadbury India Ltd.)",
                            "IsPrime": null,
                            "ProductSKUUQCId": null,
                            "ProductSKUUQC": null,
                            "IsCoupon": null,
                            "ProductOtherImage": null,
                            "ProductSKUUQCShortName": null,
                            "SP": 45,
                            "IsOffer": null,
                            "Express": null,
                            "IsFavoriate": null,
                            "CompanyId": null,
                            "ProductBarcodeId": null,
                            "Barcode": "8901233000350",
                            "CategoryName": "Chocolates",
                            "CouponResult": null,
                            "isFc": 0
                        },
                        {
                            "ProductId": 100002227,
                            "ProductName": "Haldiram Bhujia",
                            "CategoryId": 273,
                            "ProductSKU": null,
                            "ProductSkuId": 10002712,
                            "ProductImage": "https://jiomerchantsit.akamaized.net/static/product/bhujia-hal-AaramShop-10.jpg",
                            "MRP": 65,
                            "BrandId": 206,
                            "ProductSKUUQCFullName": null,
                            "BrandName": "Haldiram Mixtures",
                            "OfferText": null,
                            "CompanyName": "Haldiram Snacks Pvt Ltd",
                            "IsPrime": null,
                            "ProductSKUUQCId": null,
                            "ProductSKUUQC": null,
                            "IsCoupon": null,
                            "ProductOtherImage": null,
                            "ProductSKUUQCShortName": null,
                            "SP": 45,
                            "IsOffer": null,
                            "Express": null,
                            "IsFavoriate": null,
                            "CompanyId": null,
                            "ProductBarcodeId": null,
                            "Barcode": "8904063200051",
                            "CategoryName": "Bhujia",
                            "CouponResult": null,
                            "isFc": 0
                        },
                        {
                            "ProductId": 100007347,
                            "ProductName": "Kelloggs Chocos",
                            "CategoryId": 287,
                            "ProductSKU": null,
                            "ProductSkuId": 10008483,
                            "ProductImage": "https://jiomerchantsit.akamaized.net/static/product/chocos-AaramShop-4.jpg",
                            "MRP": 65,
                            "BrandId": 2148,
                            "ProductSKUUQCFullName": null,
                            "BrandName": "Chocos",
                            "OfferText": null,
                            "CompanyName": "Kelloggs Co",
                            "IsPrime": null,
                            "ProductSKUUQCId": null,
                            "ProductSKUUQC": null,
                            "IsCoupon": null,
                            "ProductOtherImage": null,
                            "ProductSKUUQCShortName": null,
                            "SP": 45,
                            "IsOffer": null,
                            "Express": null,
                            "IsFavoriate": null,
                            "CompanyId": null,
                            "ProductBarcodeId": null,
                            "Barcode": "8901499001399",
                            "CategoryName": "Cornflakes",
                            "CouponResult": null,
                            "isFc": 0
                        },
                        {
                            "ProductId": 100006793,
                            "ProductName": "Britannia Good Day Rich Butter Cookies",
                            "CategoryId": 115,
                            "ProductSKU": null,
                            "ProductSkuId": 10007813,
                            "ProductImage": "https://jiomerchantsit.akamaized.net/static/product/GOOD-DAY-AaramShop-65.jpg",
                            "MRP": 65,
                            "BrandId": 465,
                            "ProductSKUUQCFullName": null,
                            "BrandName": "Good Day",
                            "OfferText": null,
                            "CompanyName": "Britannia Industries Limited",
                            "IsPrime": null,
                            "ProductSKUUQCId": null,
                            "ProductSKUUQC": null,
                            "IsCoupon": null,
                            "ProductOtherImage": null,
                            "ProductSKUUQCShortName": null,
                            "SP": 45,
                            "IsOffer": null,
                            "Express": null,
                            "IsFavoriate": null,
                            "CompanyId": null,
                            "ProductBarcodeId": null,
                            "Barcode": "8901063092303",
                            "CategoryName": "Cookies",
                            "CouponResult": null,
                            "isFc": 0
                        },
                        {
                            "ProductId": 100017544,
                            "ProductName": "Haldiram Allin One Mixture",
                            "CategoryId": 63,
                            "ProductSKU": null,
                            "ProductSkuId": 10020440,
                            "ProductImage": "https://jiomerchantsit.akamaized.net/static/product/14553621761.jpg",
                            "MRP": 165,
                            "BrandId": 206,
                            "ProductSKUUQCFullName": null,
                            "BrandName": "Haldiram Mixtures",
                            "OfferText": null,
                            "CompanyName": "Haldiram Snacks Pvt Ltd",
                            "IsPrime": null,
                            "ProductSKUUQCId": null,
                            "ProductSKUUQC": null,
                            "IsCoupon": null,
                            "ProductOtherImage": null,
                            "ProductSKUUQCShortName": null,
                            "SP": 115,
                            "IsOffer": null,
                            "Express": null,
                            "IsFavoriate": null,
                            "CompanyId": null,
                            "ProductBarcodeId": null,
                            "Barcode": "871265502024",
                            "CategoryName": "Mixture",
                            "CouponResult": null,
                            "isFc": 0
                        },
                        {
                            "ProductId": 100014225,
                            "ProductName": "Dettol Sensitivep H- Balanced Hand Wash Refill",
                            "CategoryId": 10001124,
                            "ProductSKU": null,
                            "ProductSkuId": 10016538,
                            "ProductImage": "https://jiomerchantsit.akamaized.net/static/product/16-32-251217384083.jpg",
                            "MRP": 165,
                            "BrandId": 280,
                            "ProductSKUUQCFullName": null,
                            "BrandName": "Dettol",
                            "OfferText": null,
                            "CompanyName": "Reckitt Benckiser",
                            "IsPrime": null,
                            "ProductSKUUQCId": null,
                            "ProductSKUUQC": null,
                            "IsCoupon": null,
                            "ProductOtherImage": null,
                            "ProductSKUUQCShortName": null,
                            "SP": 115,
                            "IsOffer": null,
                            "Express": null,
                            "IsFavoriate": null,
                            "CompanyId": null,
                            "ProductBarcodeId": null,
                            "Barcode": "8901396387602",
                            "CategoryName": "Hand Wash",
                            "CouponResult": null,
                            "isFc": 0
                        },
                        {
                            "ProductId": 100041181,
                            "ProductName": "Sunsilk Soya Vitamin Complex Shampoo",
                            "CategoryId": 10000987,
                            "ProductSKU": null,
                            "ProductSkuId": 10046844,
                            "ProductImage": "https://jiomerchantsit.akamaized.net/static/product/1460011488.jpg",
                            "MRP": 165,
                            "BrandId": 21,
                            "ProductSKUUQCFullName": null,
                            "BrandName": "Sunsilk",
                            "OfferText": null,
                            "CompanyName": "Hindustan Unilever",
                            "IsPrime": null,
                            "ProductSKUUQCId": null,
                            "ProductSKUUQC": null,
                            "IsCoupon": null,
                            "ProductOtherImage": null,
                            "ProductSKUUQCShortName": null,
                            "SP": 115,
                            "IsOffer": null,
                            "Express": null,
                            "IsFavoriate": null,
                            "CompanyId": null,
                            "ProductBarcodeId": null,
                            "Barcode": "8901030445767",
                            "CategoryName": "Hair Shampoo",
                            "CouponResult": null,
                            "isFc": 0
                        },
                        {
                            "ProductId": 100039238,
                            "ProductName": "Act Ii Inst Popcorn Classic Sltd",
                            "CategoryId": 137,
                            "ProductSKU": null,
                            "ProductSkuId": 10044650,
                            "ProductImage": "https://jiomerchantsit.akamaized.net/static/product/no_image_found.png",
                            "MRP": 165,
                            "BrandId": 10004166,
                            "ProductSKUUQCFullName": null,
                            "BrandName": "Agro Tech Foods",
                            "OfferText": null,
                            "CompanyName": "Sundrop Superlite Advncd Rsf Oil",
                            "IsPrime": null,
                            "ProductSKUUQCId": null,
                            "ProductSKUUQC": null,
                            "IsCoupon": null,
                            "ProductOtherImage": null,
                            "ProductSKUUQCShortName": null,
                            "SP": 115,
                            "IsOffer": null,
                            "Express": null,
                            "IsFavoriate": null,
                            "CompanyId": null,
                            "ProductBarcodeId": null,
                            "Barcode": "8901512540102",
                            "CategoryName": "Instant Popcorn",
                            "CouponResult": null,
                            "isFc": 0
                        },
                        {
                            "ProductId": 100006790,
                            "ProductName": "Mc Vities Cashew Cookies",
                            "CategoryId": 115,
                            "ProductSKU": null,
                            "ProductSkuId": 10007810,
                            "ProductImage": "https://jiomerchantsit.akamaized.net/static/product/13-23-3139789834.jpg",
                            "MRP": 165,
                            "BrandId": 10003780,
                            "ProductSKUUQCFullName": null,
                            "BrandName": "Mc Vities",
                            "OfferText": null,
                            "CompanyName": "United Biscuits( U K) Ltd",
                            "IsPrime": null,
                            "ProductSKUUQCId": null,
                            "ProductSKUUQC": null,
                            "IsCoupon": null,
                            "ProductOtherImage": null,
                            "ProductSKUUQCShortName": null,
                            "SP": 115,
                            "IsOffer": null,
                            "Express": null,
                            "IsFavoriate": null,
                            "CompanyId": null,
                            "ProductBarcodeId": null,
                            "Barcode": "8906033740215",
                            "CategoryName": "Cookies",
                            "CouponResult": null,
                            "isFc": 0
                        }
                    ],
                    "miscellaneous": null,
                    "stores": null,
                    "banners": null
                }
            },
            {
                "type": 4,
                "subType": 4,
                "title": "",
                "deepLink": "",
                "deepLinkText": "",
                "bgColor": "",
                "data": {
                    "products": null,
                    "miscellaneous": null,
                    "stores": null,
                    "banners": [
                        {
                            "imageUrl": "https://pp-static.jiomoney.com/static/capp/android/drawable-xhdpi/offer_banner.png",
                            "deepLink": "",
                            "bannerId": 4,
                            "imageResolutionSupport": 1
                        },
                        {
                            "imageUrl": "https://jiomerchantsit.akamaized.net/static/capp/ios/3x/Get-Off-on-Nuts.png",
                            "deepLink": "",
                            "bannerId": 5,
                            "imageResolutionSupport": 1
                        },
                        {
                            "imageUrl": "https://jiomerchantsit.akamaized.net/static/capp/ios/3x/Get-Upto-Off-on-Fresh-Fruits.png",
                            "deepLink": "",
                            "bannerId": 6,
                            "imageResolutionSupport": 1
                        }
                    ]
                }
            },
            {
                "type": 5,
                "subType": 2,
                "title": "TOP OFFERS",
                "deepLink": "",
                "deepLinkText": "See more",
                "bgColor": "",
                "data": {
                    "products": [
                        {
                            "ProductId": 100015385,
                            "ProductName": "Nestea Iced Tea Lemon Flavour",
                            "CategoryId": 177,
                            "ProductSKU": null,
                            "ProductSkuId": 10017970,
                            "ProductImage": "https://jiomerchantsit.akamaized.net/static/product/nesteaicedtealemonflavour500-aaramshop.jpg",
                            "MRP": 65,
                            "BrandId": 108,
                            "ProductSKUUQCFullName": null,
                            "BrandName": "Nestea",
                            "OfferText": null,
                            "CompanyName": "Nestle India Limited",
                            "IsPrime": null,
                            "ProductSKUUQCId": null,
                            "ProductSKUUQC": null,
                            "IsCoupon": true,
                            "ProductOtherImage": null,
                            "ProductSKUUQCShortName": null,
                            "SP": 45,
                            "IsOffer": null,
                            "Express": null,
                            "IsFavoriate": null,
                            "CompanyId": null,
                            "ProductBarcodeId": null,
                            "Barcode": "8901058816563",
                            "CategoryName": "Ice Tea",
                            "CouponResult": null,
                            "isFc": 0
                        },
                        {
                            "ProductId": 100009282,
                            "ProductName": "Nivea Whitening Fruity Deodorant For Women",
                            "CategoryId": 10000697,
                            "ProductSKU": null,
                            "ProductSkuId": 10010675,
                            "ProductImage": "https://jiomerchantsit.akamaized.net/static/product/1460613833.jpg",
                            "MRP": 65,
                            "BrandId": 89,
                            "ProductSKUUQCFullName": null,
                            "BrandName": "Nivea Deodarants",
                            "OfferText": null,
                            "CompanyName": "Nivea India Pvt. Ltd. (Beiersdorf AG)",
                            "IsPrime": null,
                            "ProductSKUUQCId": null,
                            "ProductSKUUQC": null,
                            "IsCoupon": null,
                            "ProductOtherImage": null,
                            "ProductSKUUQCShortName": null,
                            "SP": 45,
                            "IsOffer": null,
                            "Express": null,
                            "IsFavoriate": null,
                            "CompanyId": null,
                            "ProductBarcodeId": null,
                            "Barcode": "4005808667758",
                            "CategoryName": "Deodorants",
                            "CouponResult": null,
                            "isFc": 0
                        },
                        {
                            "ProductId": 100041181,
                            "ProductName": "Sunsilk Soya Vitamin Complex Shampoo",
                            "CategoryId": 10000987,
                            "ProductSKU": null,
                            "ProductSkuId": 10046844,
                            "ProductImage": "https://jiomerchantsit.akamaized.net/static/product/1460011488.jpg",
                            "MRP": 165,
                            "BrandId": 21,
                            "ProductSKUUQCFullName": null,
                            "BrandName": "Sunsilk",
                            "OfferText": null,
                            "CompanyName": "Hindustan Unilever",
                            "IsPrime": null,
                            "ProductSKUUQCId": null,
                            "ProductSKUUQC": null,
                            "IsCoupon": null,
                            "ProductOtherImage": null,
                            "ProductSKUUQCShortName": null,
                            "SP": 115,
                            "IsOffer": null,
                            "Express": null,
                            "IsFavoriate": null,
                            "CompanyId": null,
                            "ProductBarcodeId": null,
                            "Barcode": "8901030445767",
                            "CategoryName": "Hair Shampoo",
                            "CouponResult": null,
                            "isFc": 0
                        },
                        {
                            "ProductId": 1000003914,
                            "ProductName": "Gillette Mach3 Manual Shaving Razor Blades Cartridges",
                            "CategoryId": 156,
                            "ProductSKU": null,
                            "ProductSkuId": 10004556,
                            "ProductImage": "https://jiomerchantsit.akamaized.net/static/product/Gillette-Mach3-Manual-12-AaramShop-95.jpg",
                            "MRP": 65,
                            "BrandId": 67,
                            "ProductSKUUQCFullName": null,
                            "BrandName": "Gillette",
                            "OfferText": null,
                            "CompanyName": "Procter & Gamble India Ltd",
                            "IsPrime": null,
                            "ProductSKUUQCId": null,
                            "ProductSKUUQC": null,
                            "IsCoupon": null,
                            "ProductOtherImage": null,
                            "ProductSKUUQCShortName": null,
                            "SP": 45,
                            "IsOffer": null,
                            "Express": null,
                            "IsFavoriate": null,
                            "CompanyId": null,
                            "ProductBarcodeId": null,
                            "Barcode": "4902430658270",
                            "CategoryName": "Cartridges",
                            "CouponResult": null,
                            "isFc": 0
                        },
                        {
                            "ProductId": 100016645,
                            "ProductName": "M D H Amchur Powder",
                            "CategoryId": 10001016,
                            "ProductSKU": null,
                            "ProductSkuId": 10019401,
                            "ProductImage": "https://jiomerchantsit.akamaized.net/static/product/04-52-031672411443.jpg",
                            "MRP": 165,
                            "BrandId": 10003838,
                            "ProductSKUUQCFullName": null,
                            "BrandName": "M D H Masale",
                            "OfferText": null,
                            "CompanyName": "M D H Limited",
                            "IsPrime": null,
                            "ProductSKUUQCId": null,
                            "ProductSKUUQC": null,
                            "IsCoupon": null,
                            "ProductOtherImage": null,
                            "ProductSKUUQCShortName": null,
                            "SP": 115,
                            "IsOffer": null,
                            "Express": null,
                            "IsFavoriate": null,
                            "CompanyId": null,
                            "ProductBarcodeId": null,
                            "Barcode": "8902167000300",
                            "CategoryName": "Powdered MRPices",
                            "CouponResult": null,
                            "isFc": 0
                        },
                        {
                            "ProductId": 100018859,
                            "ProductName": "Bagrrys Porridge White Oats Jar",
                            "CategoryId": 78,
                            "ProductSKU": null,
                            "ProductSkuId": 10022013,
                            "ProductImage": "https://jiomerchantsit.akamaized.net/static/product/14547424781.jpg",
                            "MRP": 65,
                            "BrandId": 672,
                            "ProductSKUUQCFullName": null,
                            "BrandName": "Bagrrys",
                            "OfferText": null,
                            "CompanyName": "Bagrrys India Limited",
                            "IsPrime": null,
                            "ProductSKUUQCId": null,
                            "ProductSKUUQC": null,
                            "IsCoupon": null,
                            "ProductOtherImage": null,
                            "ProductSKUUQCShortName": null,
                            "SP": 45,
                            "IsOffer": null,
                            "Express": null,
                            "IsFavoriate": null,
                            "CompanyId": null,
                            "ProductBarcodeId": null,
                            "Barcode": "8902710100112",
                            "CategoryName": "Oats",
                            "CouponResult": null,
                            "isFc": 0
                        },
                        {
                            "ProductId": 100001160,
                            "ProductName": "Aashirvaad Atta With Multigrains",
                            "CategoryId": 120,
                            "ProductSKU": null,
                            "ProductSkuId": 10001303,
                            "ProductImage": "https://jiomerchantsit.akamaized.net/static/product/04-17-28848812574.jpg",
                            "MRP": 65,
                            "BrandId": 370,
                            "ProductSKUUQCFullName": null,
                            "BrandName": "Aashirvaad",
                            "OfferText": null,
                            "CompanyName": "ITC Limited",
                            "IsPrime": null,
                            "ProductSKUUQCId": null,
                            "ProductSKUUQC": null,
                            "IsCoupon": null,
                            "ProductOtherImage": null,
                            "ProductSKUUQCShortName": null,
                            "SP": 45,
                            "IsOffer": null,
                            "Express": null,
                            "IsFavoriate": null,
                            "CompanyId": null,
                            "ProductBarcodeId": null,
                            "Barcode": "8901725121624",
                            "CategoryName": "Atta",
                            "CouponResult": null,
                            "isFc": 0
                        },
                        {
                            "ProductId": 100005203,
                            "ProductName": "Cadbury Gems",
                            "CategoryId": 90,
                            "ProductSKU": null,
                            "ProductSkuId": 10006009,
                            "ProductImage": "https://jiomerchantsit.akamaized.net/static/product/gems_AaramShop1.jpg",
                            "MRP": 65,
                            "BrandId": 1257,
                            "ProductSKUUQCFullName": null,
                            "BrandName": "Cadbury Gems",
                            "OfferText": null,
                            "CompanyName": "Mondelez India Foods Pvt Ltd (Formerly Cadbury India Ltd.)",
                            "IsPrime": null,
                            "ProductSKUUQCId": null,
                            "ProductSKUUQC": null,
                            "IsCoupon": null,
                            "ProductOtherImage": null,
                            "ProductSKUUQCShortName": null,
                            "SP": 45,
                            "IsOffer": null,
                            "Express": null,
                            "IsFavoriate": null,
                            "CompanyId": null,
                            "ProductBarcodeId": null,
                            "Barcode": "8901233000350",
                            "CategoryName": "Chocolates",
                            "CouponResult": null,
                            "isFc": 0
                        },
                        {
                            "ProductId": 100002227,
                            "ProductName": "Haldiram Bhujia",
                            "CategoryId": 273,
                            "ProductSKU": null,
                            "ProductSkuId": 10002712,
                            "ProductImage": "https://jiomerchantsit.akamaized.net/static/product/bhujia-hal-AaramShop-10.jpg",
                            "MRP": 65,
                            "BrandId": 206,
                            "ProductSKUUQCFullName": null,
                            "BrandName": "Haldiram Mixtures",
                            "OfferText": null,
                            "CompanyName": "Haldiram Snacks Pvt Ltd",
                            "IsPrime": null,
                            "ProductSKUUQCId": null,
                            "ProductSKUUQC": null,
                            "IsCoupon": null,
                            "ProductOtherImage": null,
                            "ProductSKUUQCShortName": null,
                            "SP": 45,
                            "IsOffer": null,
                            "Express": null,
                            "IsFavoriate": null,
                            "CompanyId": null,
                            "ProductBarcodeId": null,
                            "Barcode": "8904063200051",
                            "CategoryName": "Bhujia",
                            "CouponResult": null,
                            "isFc": 0
                        },
                        {
                            "ProductId": 100006793,
                            "ProductName": "Britannia Good Day Rich Butter Cookies",
                            "CategoryId": 115,
                            "ProductSKU": null,
                            "ProductSkuId": 10007813,
                            "ProductImage": "https://jiomerchantsit.akamaized.net/static/product/GOOD-DAY-AaramShop-65.jpg",
                            "MRP": 65,
                            "BrandId": 465,
                            "ProductSKUUQCFullName": null,
                            "BrandName": "Good Day",
                            "OfferText": null,
                            "CompanyName": "Britannia Industries Limited",
                            "IsPrime": null,
                            "ProductSKUUQCId": null,
                            "ProductSKUUQC": null,
                            "IsCoupon": null,
                            "ProductOtherImage": null,
                            "ProductSKUUQCShortName": null,
                            "SP": 45,
                            "IsOffer": null,
                            "Express": null,
                            "IsFavoriate": null,
                            "CompanyId": null,
                            "ProductBarcodeId": null,
                            "Barcode": "8901063092303",
                            "CategoryName": "Cookies",
                            "CouponResult": null,
                            "isFc": 0
                        },
                        {
                            "ProductId": 100014225,
                            "ProductName": "Dettol Sensitivep H- Balanced Hand Wash Refill",
                            "CategoryId": 10001124,
                            "ProductSKU": null,
                            "ProductSkuId": 10016538,
                            "ProductImage": "https://jiomerchantsit.akamaized.net/static/product/16-32-251217384083.jpg",
                            "MRP": 165,
                            "BrandId": 280,
                            "ProductSKUUQCFullName": null,
                            "BrandName": "Dettol",
                            "OfferText": null,
                            "CompanyName": "Reckitt Benckiser",
                            "IsPrime": null,
                            "ProductSKUUQCId": null,
                            "ProductSKUUQC": null,
                            "IsCoupon": null,
                            "ProductOtherImage": null,
                            "ProductSKUUQCShortName": null,
                            "SP": 115,
                            "IsOffer": null,
                            "Express": null,
                            "IsFavoriate": null,
                            "CompanyId": null,
                            "ProductBarcodeId": null,
                            "Barcode": "8901396387602",
                            "CategoryName": "Hand Wash",
                            "CouponResult": null,
                            "isFc": 0
                        },
                        {
                            "ProductId": 100006790,
                            "ProductName": "Mc Vities Cashew Cookies",
                            "CategoryId": 115,
                            "ProductSKU": null,
                            "ProductSkuId": 10007810,
                            "ProductImage": "https://jiomerchantsit.akamaized.net/static/product/13-23-3139789834.jpg",
                            "MRP": 165,
                            "BrandId": 10003780,
                            "ProductSKUUQCFullName": null,
                            "BrandName": "Mc Vities",
                            "OfferText": null,
                            "CompanyName": "United Biscuits( U K) Ltd",
                            "IsPrime": null,
                            "ProductSKUUQCId": null,
                            "ProductSKUUQC": null,
                            "IsCoupon": null,
                            "ProductOtherImage": null,
                            "ProductSKUUQCShortName": null,
                            "SP": 115,
                            "IsOffer": null,
                            "Express": null,
                            "IsFavoriate": null,
                            "CompanyId": null,
                            "ProductBarcodeId": null,
                            "Barcode": "8906033740215",
                            "CategoryName": "Cookies",
                            "CouponResult": null,
                            "isFc": 0
                        },
                        {
                            "ProductId": 100001738,
                            "ProductName": "Nivea Creme Soft",
                            "CategoryId": 99,
                            "ProductSKU": null,
                            "ProductSkuId": 10002045,
                            "ProductImage": "https://jiomerchantsit.akamaized.net/static/product/13-32-48245070032.jpg",
                            "MRP": 165,
                            "BrandId": 86,
                            "ProductSKUUQCFullName": null,
                            "BrandName": "Nivea Bath Care",
                            "OfferText": null,
                            "CompanyName": "Nivea India Pvt. Ltd. (Beiersdorf AG)",
                            "IsPrime": null,
                            "ProductSKUUQCId": null,
                            "ProductSKUUQC": null,
                            "IsCoupon": null,
                            "ProductOtherImage": null,
                            "ProductSKUUQCShortName": null,
                            "SP": 115,
                            "IsOffer": null,
                            "Express": null,
                            "IsFavoriate": null,
                            "CompanyId": null,
                            "ProductBarcodeId": null,
                            "Barcode": "4005808789580",
                            "CategoryName": "Face Cream",
                            "CouponResult": null,
                            "isFc": 0
                        },
                        {
                            "ProductId": 100005099,
                            "ProductName": "Lays Classic Salted",
                            "CategoryId": 75,
                            "ProductSKU": null,
                            "ProductSkuId": 10047934,
                            "ProductImage": "https://jiomerchantsit.akamaized.net/static/product/no_image_found.png",
                            "MRP": 65,
                            "BrandId": 1869,
                            "ProductSKUUQCFullName": null,
                            "BrandName": "Lays",
                            "OfferText": null,
                            "CompanyName": "PepsiCo India",
                            "IsPrime": null,
                            "ProductSKUUQCId": null,
                            "ProductSKUUQC": null,
                            "IsCoupon": null,
                            "ProductOtherImage": null,
                            "ProductSKUUQCShortName": null,
                            "SP": 45,
                            "IsOffer": null,
                            "Express": null,
                            "IsFavoriate": null,
                            "CompanyId": null,
                            "ProductBarcodeId": null,
                            "Barcode": "8901491101837",
                            "CategoryName": "Chips",
                            "CouponResult": null,
                            "isFc": 0
                        },
                        {
                            "ProductId": 100010947,
                            "ProductName": "Clearasil Daily Use Facewash",
                            "CategoryId": 10001132,
                            "ProductSKU": null,
                            "ProductSkuId": 10012682,
                            "ProductImage": "https://jiomerchantsit.akamaized.net/static/product/12-25-421976706774.jpg",
                            "MRP": 65,
                            "BrandId": 290,
                            "ProductSKUUQCFullName": null,
                            "BrandName": "Clearasil",
                            "OfferText": null,
                            "CompanyName": "Reckitt Benckiser",
                            "IsPrime": null,
                            "ProductSKUUQCId": null,
                            "ProductSKUUQC": null,
                            "IsCoupon": null,
                            "ProductOtherImage": null,
                            "ProductSKUUQCShortName": null,
                            "SP": 45,
                            "IsOffer": null,
                            "Express": null,
                            "IsFavoriate": null,
                            "CompanyId": null,
                            "ProductBarcodeId": null,
                            "Barcode": "8901396608004",
                            "CategoryName": "Face Wash",
                            "CouponResult": null,
                            "isFc": 0
                        },
                        {
                            "ProductId": 100014452,
                            "ProductName": "Complan For Growth Natural",
                            "CategoryId": 10002160,
                            "ProductSKU": null,
                            "ProductSkuId": 10016816,
                            "ProductImage": "https://jiomerchantsit.akamaized.net/static/product/1457936081.jpg",
                            "MRP": 65,
                            "BrandId": 2094,
                            "ProductSKUUQCFullName": null,
                            "BrandName": "Complan",
                            "OfferText": null,
                            "CompanyName": "The Kraft Heinz Company",
                            "IsPrime": null,
                            "ProductSKUUQCId": null,
                            "ProductSKUUQC": null,
                            "IsCoupon": null,
                            "ProductOtherImage": null,
                            "ProductSKUUQCShortName": null,
                            "SP": 45,
                            "IsOffer": null,
                            "Express": null,
                            "IsFavoriate": null,
                            "CompanyId": null,
                            "ProductBarcodeId": null,
                            "Barcode": "8901542013607",
                            "CategoryName": "Health Drinks",
                            "CouponResult": null,
                            "isFc": 0
                        },
                        {
                            "ProductId": 100007347,
                            "ProductName": "Kelloggs Chocos",
                            "CategoryId": 287,
                            "ProductSKU": null,
                            "ProductSkuId": 10008483,
                            "ProductImage": "https://jiomerchantsit.akamaized.net/static/product/chocos-AaramShop-4.jpg",
                            "MRP": 65,
                            "BrandId": 2148,
                            "ProductSKUUQCFullName": null,
                            "BrandName": "Chocos",
                            "OfferText": null,
                            "CompanyName": "Kelloggs Co",
                            "IsPrime": null,
                            "ProductSKUUQCId": null,
                            "ProductSKUUQC": null,
                            "IsCoupon": null,
                            "ProductOtherImage": null,
                            "ProductSKUUQCShortName": null,
                            "SP": 45,
                            "IsOffer": null,
                            "Express": null,
                            "IsFavoriate": null,
                            "CompanyId": null,
                            "ProductBarcodeId": null,
                            "Barcode": "8901499001399",
                            "CategoryName": "Cornflakes",
                            "CouponResult": null,
                            "isFc": 0
                        },
                        {
                            "ProductId": 100017544,
                            "ProductName": "Haldiram Allin One Mixture",
                            "CategoryId": 63,
                            "ProductSKU": null,
                            "ProductSkuId": 10020440,
                            "ProductImage": "https://jiomerchantsit.akamaized.net/static/product/14553621761.jpg",
                            "MRP": 165,
                            "BrandId": 206,
                            "ProductSKUUQCFullName": null,
                            "BrandName": "Haldiram Mixtures",
                            "OfferText": null,
                            "CompanyName": "Haldiram Snacks Pvt Ltd",
                            "IsPrime": null,
                            "ProductSKUUQCId": null,
                            "ProductSKUUQC": null,
                            "IsCoupon": null,
                            "ProductOtherImage": null,
                            "ProductSKUUQCShortName": null,
                            "SP": 115,
                            "IsOffer": null,
                            "Express": null,
                            "IsFavoriate": null,
                            "CompanyId": null,
                            "ProductBarcodeId": null,
                            "Barcode": "871265502024",
                            "CategoryName": "Mixture",
                            "CouponResult": null,
                            "isFc": 0
                        },
                        {
                            "ProductId": 100037928,
                            "ProductName": "Delmonte Fruit Fiesta Cocktail",
                            "CategoryId": 442,
                            "ProductSKU": null,
                            "ProductSkuId": 10043265,
                            "ProductImage": "https://jiomerchantsit.akamaized.net/static/product/no_image_found.png",
                            "MRP": 165,
                            "BrandId": 10003873,
                            "ProductSKUUQCFullName": null,
                            "BrandName": "Del Monte Phils",
                            "OfferText": null,
                            "CompanyName": "Delmonte Fruit Fiesta Cocktail",
                            "IsPrime": null,
                            "ProductSKUUQCId": null,
                            "ProductSKUUQC": null,
                            "IsCoupon": null,
                            "ProductOtherImage": null,
                            "ProductSKUUQCShortName": null,
                            "SP": 115,
                            "IsOffer": null,
                            "Express": null,
                            "IsFavoriate": null,
                            "CompanyId": null,
                            "ProductBarcodeId": null,
                            "Barcode": "4800024572516",
                            "CategoryName": "Imported Veg/Fruits",
                            "CouponResult": null,
                            "isFc": 0
                        },
                        {
                            "ProductId": 100039238,
                            "ProductName": "Act Ii Inst Popcorn Classic Sltd",
                            "CategoryId": 137,
                            "ProductSKU": null,
                            "ProductSkuId": 10044650,
                            "ProductImage": "https://jiomerchantsit.akamaized.net/static/product/no_image_found.png",
                            "MRP": 165,
                            "BrandId": 10004166,
                            "ProductSKUUQCFullName": null,
                            "BrandName": "Agro Tech Foods",
                            "OfferText": null,
                            "CompanyName": "Sundrop Superlite Advncd Rsf Oil",
                            "IsPrime": null,
                            "ProductSKUUQCId": null,
                            "ProductSKUUQC": null,
                            "IsCoupon": null,
                            "ProductOtherImage": null,
                            "ProductSKUUQCShortName": null,
                            "SP": 115,
                            "IsOffer": null,
                            "Express": null,
                            "IsFavoriate": null,
                            "CompanyId": null,
                            "ProductBarcodeId": null,
                            "Barcode": "8901512540102",
                            "CategoryName": "Instant Popcorn",
                            "CouponResult": null,
                            "isFc": 0
                        }
                    ],
                    "miscellaneous": null,
                    "stores": null,
                    "banners": null
                }
            },
            {
                "type": 6,
                "subType": 1,
                "title": "SHOP BY CATEGORIES",
                "deepLink": "",
                "deepLinkText": "See more",
                "bgColor": "",
                "data": {
                    "products": null,
                    "miscellaneous": [
                        {
                            "imageUrl": "https://jiomerchantsit.akamaized.net/static/capp/ios/3x/g3-BabyCare.png",
                            "deepLink": "",
                            "name": "Baby Care",
                            "mscId": 1,
                            "imageResolutionSupport": 1
                        },
                        {
                            "imageUrl": "https://jiomerchantsit.akamaized.net/static/capp/ios/3x/g3-Beauty-Personal-Care.png",
                            "deepLink": "",
                            "name": "Beauty & Personal Care",
                            "mscId": 2,
                            "imageResolutionSupport": 1
                        },
                        {
                            "imageUrl": "https://jiomerchantsit.akamaized.net/static/capp/ios/3x/g3-Cleaning-Hosuehold-Care.png",
                            "deepLink": "",
                            "name": "Cleaning & Hosuehold Care",
                            "mscId": 3,
                            "imageResolutionSupport": 1
                        },
                        {
                            "imageUrl": "https://jiomerchantsit.akamaized.net/static/capp/ios/3x/g3-Dairy-Bakery-Egg.png",
                            "deepLink": "",
                            "name": "Dairy, Bakery & Egg",
                            "mscId": 4,
                            "imageResolutionSupport": 1
                        },
                        {
                            "imageUrl": "https://jiomerchantsit.akamaized.net/static/capp/ios/3x/g3-Foodgrains-Oil-Masala.png",
                            "deepLink": "",
                            "name": "Foodgrains, Oil & Masala",
                            "mscId": 5,
                            "imageResolutionSupport": 1
                        },
                        {
                            "imageUrl": "https://jiomerchantsit.akamaized.net/static/capp/ios/3x/g3-Fruit-Vegetables.png",
                            "deepLink": "",
                            "name": "Fruit & Vegetables",
                            "mscId": 6,
                            "imageResolutionSupport": 1
                        },
                        {
                            "imageUrl": "https://jiomerchantsit.akamaized.net/static/capp/ios/3x/g3-Packaged-Food.png",
                            "deepLink": "",
                            "name": "Packaged Food",
                            "mscId": 7,
                            "imageResolutionSupport": 1
                        },
                        {
                            "imageUrl": "https://jiomerchantsit.akamaized.net/static/capp/ios/3x/g3-Beauty-Personal-Care.png",
                            "deepLink": "",
                            "name": "Beauty & Personal Care",
                            "mscId": 8,
                            "imageResolutionSupport": 1
                        },
                        {
                            "imageUrl": "https://jiomerchantsit.akamaized.net/static/capp/ios/3x/g3-Cleaning-Hosuehold-Care.png",
                            "deepLink": "",
                            "name": "Cleaning & Hosuehold Care",
                            "mscId": 9,
                            "imageResolutionSupport": 1
                        }
                    ],
                    "stores": null,
                    "banners": null
                }
            },
            {
                "type": 7,
                "subType": 1,
                "title": "",
                "deepLink": "",
                "deepLinkText": "",
                "bgColor": "",
                "data": {
                    "products": null,
                    "miscellaneous": null,
                    "stores": null,
                    "banners": [
                        {
                            "imageUrl": "https://pp-static.jiomoney.com/static/capp/android/drawable-xhdpi/offer_banner-3.png",
                            "deepLink": "",
                            "bannerId": 7,
                            "imageResolutionSupport": 1
                        },
                        {
                            "imageUrl": "https://jiomerchantsit.akamaized.net/static/capp/ios/3x/Atta-Whole-Wheat-Off.png",
                            "deepLink": "",
                            "bannerId": 8,
                            "imageResolutionSupport": 1
                        },
                        {
                            "imageUrl": "https://jiomerchantsit.akamaized.net/static/capp/ios/3x/THe-Healthy-Bite-Off.png",
                            "deepLink": "",
                            "bannerId": 9,
                            "imageResolutionSupport": 1
                        }
                    ]
                }
            },
            {
                "type": 8,
                "subType": 1,
                "title": "POPULAR BRANDS",
                "deepLink": "",
                "deepLinkText": "See more",
                "bgColor": "",
                "data": {
                    "products": null,
                    "miscellaneous": [
                        {
                            "imageUrl": "https://pp-static.jiomoney.com/static/capp/android/drawable-xhdpi/brand.png",
                            "deepLink": "",
                            "name": "brand",
                            "mscId": 9,
                            "imageResolutionSupport": 1
                        },
                        {
                            "imageUrl": "https://pp-static.jiomoney.com/static/capp/android/drawable-xhdpi/brand-1.png",
                            "deepLink": "",
                            "name": "brand",
                            "mscId": 10,
                            "imageResolutionSupport": 1
                        },
                        {
                            "imageUrl": "https://pp-static.jiomoney.com/static/capp/android/drawable-xhdpi/brand-2.png",
                            "deepLink": "",
                            "name": "brand",
                            "mscId": 11,
                            "imageResolutionSupport": 1
                        },
                        {
                            "imageUrl": "https://pp-static.jiomoney.com/static/capp/android/drawable-xhdpi/brand-3.png",
                            "deepLink": "",
                            "name": "brand",
                            "mscId": 12,
                            "imageResolutionSupport": 1
                        }, {
                            "imageUrl": "https://pp-static.jiomoney.com/static/capp/android/drawable-xhdpi/brand.png",
                            "deepLink": "",
                            "name": "brand",
                            "mscId": 9,
                            "imageResolutionSupport": 1
                        },
                        {
                            "imageUrl": "https://pp-static.jiomoney.com/static/capp/android/drawable-xhdpi/brand-1.png",
                            "deepLink": "",
                            "name": "brand",
                            "mscId": 10,
                            "imageResolutionSupport": 1
                        },
                        {
                            "imageUrl": "https://pp-static.jiomoney.com/static/capp/android/drawable-xhdpi/brand-2.png",
                            "deepLink": "",
                            "name": "brand",
                            "mscId": 11,
                            "imageResolutionSupport": 1
                        }
                    ],
                    "stores": null,
                    "banners": null
                }
            },
            {
                "type": 9,
                "subType": 1,
                "title": "UPTO 50% OFF : SNACKS & BEVERAGES",
                "deepLink": "",
                "deepLinkText": "See more",
                "bgColor": "",
                "data": {
                    "products": null,
                    "miscellaneous": [
                        {
                            "imageUrl": "https://jiomerchantsit.akamaized.net/static/capp/ios/3x/Biscuits-Cookies.png",
                            "deepLink": "",
                            "name": "Biscuits & Cookies",
                            "mscId": 13,
                            "imageResolutionSupport": 1
                        },
                        {
                            "imageUrl": "https://jiomerchantsit.akamaized.net/static/capp/ios/3x/Candies.png",
                            "deepLink": "",
                            "name": "Candies",
                            "mscId": 14,
                            "imageResolutionSupport": 1
                        },
                        {
                            "imageUrl": "https://jiomerchantsit.akamaized.net/static/capp/ios/3x/Chocalates.png",
                            "deepLink": "",
                            "name": "Chocalates",
                            "mscId": 15,
                            "imageResolutionSupport": 1
                        },
                        {
                            "imageUrl": "https://jiomerchantsit.akamaized.net/static/capp/ios/3x/Soft-Drinks.png",
                            "deepLink": "",
                            "name": "Soft Drinks",
                            "mscId": 16,
                            "imageResolutionSupport": 1
                        }
                    ],
                    "stores": null,
                    "banners": null
                }
            }
        ],
        "name": null,
        "Id": 20
    }
}